language: cpp
sudo: false
notifications:
  email: false
  slack: anysim:q6E42mHSCjn4N2DqDzts4o6v

os: linux
dist: xenial

matrix:
  include:
    - env: COMPILER=g++-7 BUILD_TYPE=Debug
      addons: &gcc7
        apt:
          packages:
          - g++-7
          - mesa-common-dev
          - pybind11-dev
          - python-dev
          sources:
            - ubuntu-toolchain-r-test
    - env: COMPILER=g++-7 BUILD_TYPE=Release
      addons: *gcc7

install:
  - export CXX=${COMPILER}
  - ${CXX} --version
  - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.11.1-xenial
  - sudo apt update
  - sudo apt-get install -qq qt511-meta-full

before_script:
  - QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')
  - source /opt/qt511/bin/qt511-env.sh
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

script:
  - make -j 4
